// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchEventFacts(arg1:number):Promise<Array<main.EventFactDisplay>>;

export function FetchEvents(arg1:string,arg2:string):Promise<Array<main.CTEvent>>;

export function FetchFacts():Promise<Array<main.CTFactDefinition>>;

export function FetchMasterData():Promise<main.CTMasterData>;

export function FetchPersons():Promise<Array<main.Person>>;

export function GetEinsaetze():Promise<Array<main.Einsatz>>;

export function GetMusikteam():Promise<Record<string, any>>;

export function GetPersons():Promise<Array<main.Person>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetTeamleiter():Promise<Record<string, main.TeamleiterEntry>>;

export function RunUpdate():Promise<void>;

export function SaveMusikteam(arg1:Array<string>,arg2:Array<main.Dienst>):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetEinsaetze(arg1:Array<main.Einsatz>):Promise<void>;

export function SetTeamleiter(arg1:Record<string, main.TeamleiterEntry>):Promise<void>;
