// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchEventFacts(arg1) {
  return window['go']['main']['App']['FetchEventFacts'](arg1);
}

export function FetchEvents(arg1, arg2) {
  return window['go']['main']['App']['FetchEvents'](arg1, arg2);
}

export function FetchFacts() {
  return window['go']['main']['App']['FetchFacts']();
}

export function FetchMasterData() {
  return window['go']['main']['App']['FetchMasterData']();
}

export function FetchPersons() {
  return window['go']['main']['App']['FetchPersons']();
}

export function GetEinsaetze() {
  return window['go']['main']['App']['GetEinsaetze']();
}

export function GetMusikteam() {
  return window['go']['main']['App']['GetMusikteam']();
}

export function GetPersons() {
  return window['go']['main']['App']['GetPersons']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTeamleiter() {
  return window['go']['main']['App']['GetTeamleiter']();
}

export function RunUpdate() {
  return window['go']['main']['App']['RunUpdate']();
}

export function SaveMusikteam(arg1, arg2) {
  return window['go']['main']['App']['SaveMusikteam'](arg1, arg2);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SetEinsaetze(arg1) {
  return window['go']['main']['App']['SetEinsaetze'](arg1);
}

export function SetTeamleiter(arg1) {
  return window['go']['main']['App']['SetTeamleiter'](arg1);
}
